# -*- coding: utf-8 -*-
"""server

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TilCKyOxuU4imPq-gCKHXfo1Pk8bfB2k
"""

import socket

def receive_message_from_client(conn):
    while True:
        data = conn.recv(1024)
        if not data:
            break
        print('Client:', data.decode())  # Menampilkan pesan dari client
        response = input("Masukkan pesan balasan untuk client: ")  # Meminta pesan balasan dari server
        conn.sendall(response.encode())  # Mengirim pesan balasan ke client

host = socket.gethostname()
port = 12345
s = socket.socket()
s.bind((host, port))
s.listen(5)
print('Server listening on', host, 'port', port)

while True:
    conn, addr = s.accept()
    print('Got connection from', addr[0], '(', addr[1], ')')
    print('Thank you for connecting')

    # Panggil fungsi untuk menerima pesan dari file client
    receive_message_from_client(conn)

    conn.close()


    


# import socket

# host = socket.gethostname()
# port = 12345
# s = socket.socket()
# s.bind((host, port))
# s.listen(5)
# print('Server listening on', host, 'port', port)

# while True:
#     conn, addr = s.accept()
#     print('Got connection from', addr[0], '(', addr[1], ')')
#     print('Thank you for connecting')
#     while True:
#         data = conn.recv(1024)
#         if not data:
#             break
#         print('Client:', data.decode())  # Menampilkan pesan dari client
#         conn.sendall(data)
#     conn.close()

